### ISSUE TITLE
Call to a member function getPath() on null

### ISSUE THREAD

**Issue by 8191** [rullzer/previewgenerator#101]
After scanning several folders the preview generation (generate-all) threw an exception:

```
An unhandled exception has been thrown:
Error: Call to a member function getPath() on null in /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php:72
Stack trace:
#0 /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php(53): OC\Preview\GeneratorHelper->getViewAndPath(NULL)
#1 /var/www/nextcloud/lib/private/Preview/Generator.php(166): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\JPEG), Object(OC\Files\Node\File), 2048, 2048)
#2 /var/www/nextcloud/lib/private/Preview/Generator.php(110): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'image/jpeg')
#3 /var/www/nextcloud/lib/private/PreviewManager.php(201): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', 'image/jpeg')
#4 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(175): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#5 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(159): OCA\PreviewGenerator\Command\Generate->parseFile(Object(OC\Files\Node\File))
#6 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(157): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#7 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(157): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#8 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(157): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#9 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(157): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#10 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(138): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder))
#11 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(118): OCA\PreviewGenerator\Command\Generate->generateUserPreviews(Object(OC\User\User))
#12 /var/www/nextcloud/lib/private/User/Manager.php(476): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}(Object(OC\User\User))
#13 /var/www/nextcloud/apps/previewgenerator/lib/Command/Generate.php(119): OC\User\Manager->callForSeenUsers(Object(Closure))
#14 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(256): OCA\PreviewGenerator\Command\Generate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Outpu
t\ConsoleOutput))
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Co
nsoleOutput))
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\Generate), Object(Symfony\Component\Console\Input\Ar
gvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Cons
oleOutput))
#18 /var/www/nextcloud/lib/private/Console/Application.php(170): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutp
ut))
#19 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#20 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#21 {main}sudo -u apache php occ preview:generate-all  47117.11s user 1468.96s system 28% cpu 48:08:41.84 total
```

**Comment by joshtrichards** [comment]
This section of code is somewhat different now and this was a LONG time ago. Haven't seen any other reports. Closing this out, but don't hesitate to re-open if still happening (or create a new issue for anything similar).
