### ISSUE TITLE
Preview pregeneration takes ages since update.

### ISSUE THREAD

**Issue by GAS85** [rullzer/previewgenerator#46]
Hi,
 I have a cron job with [this script](https://github.com/GAS85/nextcloud_scripts/blob/master/nextcloud-preview.sh) to run preview pre-generation twice a day, but since update it takes days to pre generate something, almost as long as full preview generation.

 I have load around 5 new jpegs per day and 9653 at all.

 Full preview generation takes around 3 days. But it is better, because it does not works before:)

Why it takes so long?
From the logs:
```
more nextcloud.log | grep Preview
{"app":"/var/www/nextcloud/occ preview:pre-generate","message":"+++ Preview generation is Completed.    Time: 91595s +++","level":1,"time":"2017-03-20T02:26:36+01:00"}
{"app":"/var/www/nextcloud/occ preview:pre-generate","message":"+++ Starting Cron Preview generation +++","level":1,"time":"2017-03-20T13:00:02+01:00"}
{"app":"/var/www/nextcloud/occ preview:pre-generate","message":"+++ Preview generation is Completed.    Time: 800s +++","level":1,"time":"2017-03-20T13:13:22+01:00"}
{"app":"/var/www/nextcloud/occ preview:pre-generate","message":"+++ Starting Cron Preview generation +++","level":1,"time":"2017-03-21T01:00:01+01:00"}
{"app":"/var/www/nextcloud/occ preview:pre-generate","message":"+++ Preview generation is Completed.    Time: 106071s +++","level":1,"time":"2017-03-22T06:27:52+01:00"}
```

**Comment by rullzer** [comment]
Can you run the pre-generate command with `-vvv`. That should print output for each file that it is touching.

**Comment by rullzer** [comment]
Also for each file that is uploaded we generate a lot of previews. So it takes a while depending on the hardware.

**Comment by GAS85** [comment]
Thanks you, I know that it is a lot of files. basically it is generated around 300000+ png's.
I do start preview generation today, but already sohrt after start I can see that it is not really good:
```
tail next-cron.log
Generating previews for /XXX/files/S5_mini/Camera/20150802_202720.jpg
Generating previews for /XXX/files/S5_mini/Camera/20150802_202739.jpg
Generating previews for /XXX/files/S5_mini/Camera/20150802_203906.jpg
Generating previews for /XXX/files/S5_mini/Camera/20150802_203915.jpg
Generating previews for /XXX/files/S5_mini/Camera/20150802_204032.jpg
Generating previews for /XXX/files/S5_mini/Camera/20150802_204046.jpg
Generating previews for /XXX/files/S5_mini/Camera/20150802_204212.jpg
Generating previews for /XXX/files/S5_mini/Camera/20150803_142800.jpg
```
It start touching files that already saved as backup for a few mouth without any changes... This is for sure. And for each of them it is really generating previews - it takes time on my Cubietruck to do this job.
I checked touched files by process and example is here just created:
```
cd /var/www/nextcloud/data/appdata_occoqcm6kiop/preview/87954
ls -lah
total 1.4M
drwxr-xr-x     2 www-data www-data 4.0K Mar 23 08:38 .
drwxr-x--- 21874 www-data www-data 516K Mar 23 08:38 ..
-rw-r--r--     1 www-data www-data  78K Mar 23 08:38 1024-1024-crop.png
-rw-r--r--     1 www-data www-data 147K Mar 23 08:38 1024-1820.png
-rw-r--r--     1 www-data www-data  99K Mar 23 08:38 1080-1080-crop.png
-rw-r--r--     1 www-data www-data 183K Mar 23 08:37 1080-1920-max.png
-rw-r--r--     1 www-data www-data 183K Mar 23 08:38 1080-1920.png
-rw-r--r--     1 www-data www-data 2.3K Mar 23 08:37 128-128-crop.png
-rw-r--r--     1 www-data www-data 4.5K Mar 23 08:38 128-228.png
-rw-r--r--     1 www-data www-data 5.1K Mar 23 08:38 144-256.png
-rw-r--r--     1 www-data www-data  890 Mar 23 08:38 18-32.png
-rw-r--r--     1 www-data www-data 5.5K Mar 23 08:37 256-256-crop.png
-rw-r--r--     1 www-data www-data  12K Mar 23 08:38 256-455.png
-rw-r--r--     1 www-data www-data  14K Mar 23 08:38 288-512.png
-rw-r--r--     1 www-data www-data  859 Mar 23 08:37 32-32-crop.png
-rw-r--r--     1 www-data www-data 1.2K Mar 23 08:38 32-57.png
-rw-r--r--     1 www-data www-data 1.3K Mar 23 08:38 36-64.png
-rw-r--r--     1 www-data www-data  18K Mar 23 08:38 512-512-crop.png
-rw-r--r--     1 www-data www-data  36K Mar 23 08:38 512-910.png
-rw-r--r--     1 www-data www-data  46K Mar 23 08:38 576-1024.png
-rw-r--r--     1 www-data www-data 2.0K Mar 23 08:38 64-114.png
-rw-r--r--     1 www-data www-data 1.2K Mar 23 08:37 64-64-crop.png
-rw-r--r--     1 www-data www-data 2.3K Mar 23 08:38 72-128.png
```

**Comment by rullzer** [comment]
Mmmm well the app just listens to changed files. Plus if the previews are there they should not be regenerated.

Could you run the following query for me:

```sql
SELECT mtime FROM oc_filecache WHERE name = '20150802_202720.jpg';
```

**Comment by GAS85** [comment]
```
mysql> SELECT mtime FROM oc_filecache WHERE name = '20150802_202720.jpg';       
+------------+                                                                  
| mtime      |                                                                  
+------------+                                                                  
| 1438529240 |                                                                  
+------------+                                                                  
1 row in set (4.63 sec)                                                       
```

**Comment by rullzer** [comment]
Strange....

For some reason that file has been triggered for preview generation. Which is strange since the app listens to the postWrite command (https://github.com/rullzer/previewgenerator/blob/master/lib/Watcher.php#L55)

So something/someone has writen to that file. And then updated the mtime (some clients do this to preserve the original time the image was taken).

**Comment by GAS85** [comment]
I will let it run till the end, because it touching files from one user only for now. If it will continue with other users files, I will come back. Because other users are offline for a few days and it will help to find an issue e.g. in client.

**Comment by GAS85** [comment]
I believe I found the issue. Some of jpg files seems to be corrupted and this will drop an error. --> Seems they were never proceed because of this error.

It seems that app was not able to generate previews long time before, but now just started with another jpg file and proceed a lot of them (around 500 before error). That's why it take some time.

```
Generating previews for /USER/files/S5_mini/Camera/20150802_202640.jpg
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/nextcloud/lib/private/Files/Filesystem.php:719
Stack trace:
#0 /var/www/nextcloud/lib/private/legacy/image.php(597): OC\Files\Filesystem::file_get_contents('/var/www/nextcl...')
#1 /var/www/nextcloud/lib/private/Preview/Image.php(57): OC_Image->loadFromFile('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php(54): OC\Preview\Image->getThumbnail('/files/S5_mini/...', 2048, 2048, false, Object(OC\Files\View))
#3 /var/www/nextcloud/lib/private/Preview/Generator.php(155): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\JPEG), Object(OC\Files\Node\File), 2048, 2048)
#4 /var/www/nextcloud/lib/private/Preview/Generator.php(108): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'image/jpeg')
#5 /var/www/nextcloud/lib/private/PreviewManager.php(182): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', 'image/jpeg')
#6 /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(213): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#7 /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(199): OCA\PreviewGenerator\Command\PreGenerate->processFile(Object(OC\Files\Node\File))
#8 /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(170): OCA\PreviewGenerator\Command\PreGenerate->processRow(Array)
#9 /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(137): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#10 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(256): OCA\PreviewGenerator\Command\PreGenerate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\PreGenerate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/nextcloud/console.php(90): OC\Console\Application->run()
#16 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#17 {main}
```

And another run started with another file. I will recheck files from the backup, because currently after download I can't open those files any more.
```
Generating previews for /USER/files/S5_mini/Camera/20150802_202705.jpg
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/nextcloud/lib/private/Files/Filesystem.php:719
Stack trace:
#0 /var/www/nextcloud/lib/private/legacy/image.php(597): OC\Files\Filesystem::file_get_contents('/var/www/nextcl...')
#1 /var/www/nextcloud/lib/private/Preview/Image.php(57): OC_Image->loadFromFile('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php(54): OC\Preview\Image->getThumbnail('/files/S5_mini/...', 2048, 2048, false, Object(OC\Files\View))
#3 /var/www/nextcloud/lib/private/Preview/Generator.php(155): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\JPEG), Object(OC\Files\Node\File), 2048, 2048)
#4 /var/www/nextcloud/lib/private/Preview/Generator.php(108): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'image/jpeg')
#5 /var/www/nextcloud/lib/private/PreviewManager.php(182): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', 'image/jpeg')
#6 /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(213): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#7 /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(199): OCA\PreviewGenerator\Command\PreGenerate->processFile(Object(OC\Files\Node\File))
#8 /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(170): OCA\PreviewGenerator\Command\PreGenerate->processRow(Array)
#9 /var/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(137): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#10 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(256): OCA\PreviewGenerator\Command\PreGenerate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\PreGenerate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/nextcloud/console.php(90): OC\Console\Application->run()
#16 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#17 {main}
```

Thanks you for support.

**Comment by rullzer** [comment]
Ah yes. We are trying to fix this in the server. But it is hard. There was a bug before in this app where it would just keep trying and trying. Now it will fail. But the next run won't try that file again.
